/**
 *
 */

#ifndef OTHELLO_H
#define OTHELLO_H

#define OTHELLO_PROTOCOL_VERSION 2

#define OTHELLO_BOARD_LENGTH 8
#define OTHELLO_NUMBER_OF_ROOMS 32
#define OTHELLO_NUMBER_OF_PLAYERS 128
#define OTHELLO_PLAYER_NAME_LENGTH 32
#define OTHELLO_ROOM_LENGTH 2
#define OTHELLO_MESSAGE_LENGTH 256

enum othello_query_e {
  OTHELLO_QUERY_LOGIN,
  OTHELLO_QUERY_LOGOFF,
  OTHELLO_QUERY_ROOM_LIST,
  OTHELLO_QUERY_ROOM_JOIN,
  OTHELLO_QUERY_ROOM_LEAVE,
  OTHELLO_QUERY_MESSAGE,
  OTHELLO_QUERY_READY,
  OTHELLO_QUERY_NOT_READY,
  OTHELLO_QUERY_PLAY,
  OTHELLO_QUERY_ABANDON,

  OTHELLO_NOTIF_ROOM_JOIN,
  OTHELLO_NOTIF_ROOM_LEAVE,
  OTHELLO_NOTIF_MESSAGE,
  OTHELLO_NOTIF_READY,
  OTHELLO_NOTIF_NOT_READY,
  OTHELLO_NOTIF_PLAY,
  OTHELLO_NOTIF_YOUR_TURN,
  OTHELLO_NOTIF_GAME_START,
  OTHELLO_NOTIF_GAME_END,
  OTHELLO_NOTIF_ABANDON
};

enum othello_state_e {
  OTHELLO_STATE_NOT_CONNECTED,
  OTHELLO_STATE_CONNECTED,
  OTHELLO_STATE_IN_ROOM,
  OTHELLO_STATE_IN_GAME
};

enum othello_status_e {
  OTHELLO_SUCCESS,
  OTHELLO_FAILURE,
  OTHELLO_ANSWER_READ_ERROR,
  OTHELLO_GAME_FINISH,
  OTHELLO_ROOM_FULL_ERROR,
  OTHELLO_ROOM_UNKNOWN_ERROR
  /*...*/
};

typedef enum othello_query_e othello_query_t;
/*typedef enum othello_notif_e othello_notif_t;*/
typedef enum othello_state_e othello_state_t;
typedef enum othello_status_e othello_status_t;

#endif
